name: Neprekinjena dostava

on:
  push:
    branches:
      - produkcijsko-okolje
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: src/stockbotics
    strategy:
      matrix:
        node-verzija:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Uporabi Node.js ${{ matrix.node-verzija }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verzija }}
      - run: npm install
      - run: npm test

      - shell: bash
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_PRODUCTION: ${{ secrets.HEROKU_PRODUCTION }}
        run: cd ..; cd ..; git filter-branch -- --all; git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git `git subtree split --prefix src produkcijsko-okolje`:master --force
